EntityCoordinator
std::unique_ptr<ComponentManager> EntityCoordinator::mComponentManager
Referenced by GetComponentManager, GetComponentType, Init, NEW_CreateEntity, NEW_GetComponentType, RegisterComponent.
std::unique_ptr<ChunkManager> EntityCoordinator::mChunkManager
Referenced by DestroyEntity, GetComponent, GetEntityCount, GetEntityQuery, Init, NEW_CreateEntity.
std::unique_ptr<ArchetypeManager> EntityCoordinator::mArchetypeManager
Referenced by GetArchetype, Init.
void EntityCoordinator::Init()
References mArchetypeManager, mChunkManager, mComponentManager.
Referenced by initialize.
ChunkAddress EntityCoordinator::NEW_CreateEntity(Archetype arch, Spritesheet sprite)
References mChunkManager, mComponentManager.
Referenced by CreateStandardEntity.
Archetype EntityCoordinator::GetArchetype(std::vector< ComponentType > compTypes)
References mArchetypeManager.
Referenced by test.
void EntityCoordinator::DestroyEntity(ChunkAddress entity)
References mChunkManager.
void EntityCoordinator::RegisterComponent()
References mComponentManager.
Referenced by test.
ComponentType EntityCoordinator::NEW_GetComponentType()
References mComponentManager.
T& EntityCoordinator::GetComponent(ChunkAddress entity)
References mChunkManager.
Referenced by main.
ComponentType EntityCoordinator::GetComponentType()
References mComponentManager.
Referenced by PhysicsWorld::AddObjects, test, PhysicsWorld::Update, Renderer::update.
std::unique_ptr<EntityQuery> EntityCoordinator::GetEntityQuery(std::vector< ComponentType > compTypes)
References mChunkManager.
Referenced by PhysicsWorld::AddObjects, PhysicsWorld::Update, Renderer::update.
ComponentManager& EntityCoordinator::GetComponentManager()
References mComponentManager.
uint32_t EntityCoordinator::GetEntityCount()
References mChunkManager.
Referenced by main, Renderer::update.