EntityQuery
int EntityQuery::entityCount
Referenced by searchChunks, totalEntitiesFound.
std::vector<Chunk*> EntityQuery::chunks
Referenced by chunk, chunkCount, getComponentArray, searchChunks.
std::vector<ComponentType> EntityQuery::compTypes
Referenced by EntityQuery, searchChunks.
void EntityQuery::searchChunks(std::vector< Chunk * > &allChunks)
References chunks, compTypes, entityCount, Archetype::getComponentTypesArrayCopy.
EntityQuery::EntityQuery(std::vector< ComponentType > &_compTypes, std::vector< Chunk * > &allChunks)
References compTypes.
int EntityQuery::totalEntitiesFound()
References entityCount.
Referenced by PhysicsWorld::AddObjects, PhysicsWorld::Update, Renderer::update.
int EntityQuery::chunkCount()
References chunks.
Chunk * EntityQuery::chunk(int i)
References chunks.
std::vector<T*> EntityQuery::getComponentArray()
References chunks.
Referenced by PhysicsWorld::AddObjects, PhysicsWorld::Update, Renderer::update.