Transform
Position Transform::position
Referenced by generateModelMatrix, getPosition, setPosition, Transform, translate, translateModelMatrix, update.
Scale Transform::scale
Referenced by generateModelMatrix, getScale, setScale, Transform.
Rotation Transform::rotation
Referenced by getRotation, rotate, setRotation, Transform.
glm::mat4 Transform::modelMatrix
Referenced by generateModelMatrix, getModelMatrix, translateModelMatrix.
b2Body* Transform::body
Referenced by getPhysicsBody, setPhysicsBody, update.
bool Transform::positionChanged
Referenced by getModelMatrix, setPosition, translate.
bool Transform::scaleChanged
Referenced by getModelMatrix, setScale.
bool Transform::rotationChanged
Referenced by getModelMatrix, rotate, setRotation.
Transform::Transform()
Transform::Transform(float xPos, float yPos, float rot, float xScale, float yScale)
References generateModelMatrix, position, rotation, scale.
Position Transform::getPosition()
References position.
void Transform::setPosition(float x, float y)
References position, positionChanged.
Referenced by PhysicsWorld::Update.
void Transform::translate(float x, float y)
References position, positionChanged, Position::x, Position::y.
void Transform::setPhysicsBody(b2Body *newBody)
References body.
b2Body * Transform::getPhysicsBody()
References body.
void Transform::update()
References body, position.
Scale Transform::getScale()
References scale.
void Transform::setScale(float x, float y)
References scale, scaleChanged.
Rotation Transform::getRotation()
References rotation.
void Transform::setRotation(float r)
References rotation, rotationChanged.
void Transform::rotate(float rDelta)
References rotation, rotationChanged.
glm::mat4 Transform::getModelMatrix()
References generateModelMatrix, modelMatrix, positionChanged, rotationChanged, scaleChanged, translateModelMatrix.
void Transform::generateModelMatrix()
References modelMatrix, position, scale, Position::x, Scale::x, Position::y, Scale::y.
Referenced by getModelMatrix, Transform.
void Transform::translateModelMatrix()
References modelMatrix, position, Position::x, Position::y.
Referenced by getModelMatrix.