Renderer
const char * Renderer::DEFAULT_VERT_SHADER_NAME
Referenced by createDefaultShaderProgram.
const char * Renderer::DEFAULT_FRAG_SHADER_NAME
Referenced by createDefaultShaderProgram.
GLuint Renderer::vertexAttribs
Referenced by init, update.
GLuint Renderer::vertexBuffer
Referenced by init, loadVertexData.
GLuint Renderer::indicesBuffer
Referenced by init, loadIndicesData.
GLuint Renderer::defaultShaderProgram
Referenced by init, update.
glm::mat4 Renderer::projectionMatrix
Referenced by init, loadUniforms.
Camera Renderer::camera
Referenced by init, loadUniforms.
std::map<const char*, SpriteInfo> Renderer::sprites
Referenced by loadImages, loadTexture, updateTexCoord.
GLFWwindow * Renderer::setupGLFW(int *width, int *height)
References window.
Referenced by init.
int Renderer::init()
Initialize the Render tutorial.
References camera, createDefaultShaderProgram, defaultShaderProgram, gladLoadGL, indicesBuffer, loadImages, projectionMatrix, setupGLFW, vertexAttribs, vertexBuffer, window.
Referenced by initialize.
int Renderer::update(EntityCoordinator *coordinator)
References defaultShaderProgram, EntityQuery::getComponentArray, EntityCoordinator::GetComponentType, EntityCoordinator::GetEntityCount, EntityCoordinator::GetEntityQuery, loadIndicesData, loadTexture, loadUniforms, loadVertexData, RenderComponent::spriteName, EntityQuery::totalEntitiesFound, updateTexCoord, vertexAttribs, window.
Referenced by runEngine.
int Renderer::teardown()
References window.
Referenced by teardown.
GLuint Renderer::createDefaultShaderProgram()
References DEFAULT_FRAG_SHADER_NAME, DEFAULT_VERT_SHADER_NAME, MODEL_MATRIX_LOCATION, PROJECTION_MATRIX_LOCATION, FileManager::readShaderFile, uniformsLocation, VIEW_MATRIX_LOCATION.
Referenced by init.
void Renderer::loadVertexData()
References vertexBuffer, vertices.
Referenced by update.
void Renderer::loadIndicesData()
References indices, indicesBuffer.
Referenced by update.
GLuint Renderer::createTexBuffer(SpriteInfo info, stbi_uc *imgData)
References SpriteInfo::height, SpriteInfo::width.
Referenced by loadImages.
void Renderer::loadTexture(const char *spriteName)
References SpriteInfo::id, sprites.
Referenced by update.
void Renderer::loadUniforms(mat4 modelMatrix)
References camera, Camera::getViewMatrix, MODEL_MATRIX_LOCATION, PROJECTION_MATRIX_LOCATION, projectionMatrix, uniformsLocation, VIEW_MATRIX_LOCATION.
Referenced by update.
void Renderer::loadImages()
References SpriteInfo::columns, createTexBuffer, SpriteInfo::height, SpriteInfo::id, FileManager::readImageFile, SpriteInfo::rows, sprites, SpriteInfo::width.
Referenced by init.
void Renderer::updateTexCoord(RenderComponent comp, const char *spriteName)
References RenderComponent::colIndex, SpriteInfo::columns, RenderComponent::rowIndex, SpriteInfo::rows, sprites, vertices.
Referenced by update.