main.cpp
EntityCoordinator coordinator
Renderer renderer
PhysicsWorld* physicsWorld
Referenced by teardown.
Archetype standardArch
ChunkAddress turtle
Referenced by main.
ChunkAddress wall
Referenced by main.
ChunkAddress dude
Referenced by main.
int initialize()
References EntityCoordinator::Init, Renderer::init.
Referenced by main.
int test()
References EntityCoordinator::GetArchetype, EntityCoordinator::GetComponentType, EntityCoordinator::RegisterComponent.
Referenced by main.
ChunkAddress CreateStandardEntity()
References EntityCoordinator::NEW_CreateEntity.
Referenced by main.
int runEngine()
References PhysicsWorld::Update, Renderer::update.
Referenced by main.
int teardown()
References physicsWorld, Renderer::teardown.
Referenced by main.
int main()
References PhysicsWorld::AddObjects, CreateStandardEntity, dude, EntityCoordinator::GetComponent, EntityCoordinator::GetEntityCount, initialize, runEngine, teardown, test, turtle, wall, window.