glad.c
_GLAD_IS_SOME_NEW_VERSION
typedef void* APIENTRYP PFNGLXGETPROCADDRESSPROC_PRIVATE(const char *)(const char *)
void* libGL
Referenced by get_proc.
PFNGLXGETPROCADDRESSPROC_PRIVATE gladGetProcAddressPtr
Referenced by get_proc.
struct gladGLversionStruct GLVersion
int max_loaded_major
int max_loaded_minor
const char* exts
Referenced by has_ext.
int num_exts_i
Referenced by free_exts, has_ext.
char** exts_i
Referenced by get_exts.
int GLAD_GL_VERSION_1_0
int GLAD_GL_VERSION_1_1
int GLAD_GL_VERSION_1_2
int GLAD_GL_VERSION_1_3
int GLAD_GL_VERSION_1_4
int GLAD_GL_VERSION_1_5
int GLAD_GL_VERSION_2_0
int GLAD_GL_VERSION_2_1
int GLAD_GL_VERSION_3_0
int GLAD_GL_VERSION_3_1
int GLAD_GL_VERSION_3_2
int GLAD_GL_VERSION_3_3
PFNGLACTIVETEXTUREPROC glad_glActiveTexture
PFNGLATTACHSHADERPROC glad_glAttachShader
PFNGLBEGINCONDITIONALRENDERPROC glad_glBeginConditionalRender
PFNGLBEGINQUERYPROC glad_glBeginQuery
PFNGLBEGINTRANSFORMFEEDBACKPROC glad_glBeginTransformFeedback
PFNGLBINDATTRIBLOCATIONPROC glad_glBindAttribLocation
PFNGLBINDBUFFERPROC glad_glBindBuffer
PFNGLBINDBUFFERBASEPROC glad_glBindBufferBase
PFNGLBINDBUFFERRANGEPROC glad_glBindBufferRange
PFNGLBINDFRAGDATALOCATIONPROC glad_glBindFragDataLocation
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glad_glBindFragDataLocationIndexed
PFNGLBINDFRAMEBUFFERPROC glad_glBindFramebuffer
PFNGLBINDRENDERBUFFERPROC glad_glBindRenderbuffer
PFNGLBINDSAMPLERPROC glad_glBindSampler
PFNGLBINDTEXTUREPROC glad_glBindTexture
PFNGLBINDVERTEXARRAYPROC glad_glBindVertexArray
PFNGLBLENDCOLORPROC glad_glBlendColor
PFNGLBLENDEQUATIONPROC glad_glBlendEquation
PFNGLBLENDEQUATIONSEPARATEPROC glad_glBlendEquationSeparate
PFNGLBLENDFUNCPROC glad_glBlendFunc
PFNGLBLENDFUNCSEPARATEPROC glad_glBlendFuncSeparate
PFNGLBLITFRAMEBUFFERPROC glad_glBlitFramebuffer
PFNGLBUFFERDATAPROC glad_glBufferData
PFNGLBUFFERSUBDATAPROC glad_glBufferSubData
PFNGLCHECKFRAMEBUFFERSTATUSPROC glad_glCheckFramebufferStatus
PFNGLCLAMPCOLORPROC glad_glClampColor
PFNGLCLEARPROC glad_glClear
PFNGLCLEARBUFFERFIPROC glad_glClearBufferfi
PFNGLCLEARBUFFERFVPROC glad_glClearBufferfv
PFNGLCLEARBUFFERIVPROC glad_glClearBufferiv
PFNGLCLEARBUFFERUIVPROC glad_glClearBufferuiv
PFNGLCLEARCOLORPROC glad_glClearColor
PFNGLCLEARDEPTHPROC glad_glClearDepth
PFNGLCLEARSTENCILPROC glad_glClearStencil
PFNGLCLIENTWAITSYNCPROC glad_glClientWaitSync
PFNGLCOLORMASKPROC glad_glColorMask
PFNGLCOLORMASKIPROC glad_glColorMaski
PFNGLCOLORP3UIPROC glad_glColorP3ui
PFNGLCOLORP3UIVPROC glad_glColorP3uiv
PFNGLCOLORP4UIPROC glad_glColorP4ui
PFNGLCOLORP4UIVPROC glad_glColorP4uiv
PFNGLCOMPILESHADERPROC glad_glCompileShader
PFNGLCOMPRESSEDTEXIMAGE1DPROC glad_glCompressedTexImage1D
PFNGLCOMPRESSEDTEXIMAGE2DPROC glad_glCompressedTexImage2D
PFNGLCOMPRESSEDTEXIMAGE3DPROC glad_glCompressedTexImage3D
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glad_glCompressedTexSubImage1D
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glad_glCompressedTexSubImage2D
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glad_glCompressedTexSubImage3D
PFNGLCOPYBUFFERSUBDATAPROC glad_glCopyBufferSubData
PFNGLCOPYTEXIMAGE1DPROC glad_glCopyTexImage1D
PFNGLCOPYTEXIMAGE2DPROC glad_glCopyTexImage2D
PFNGLCOPYTEXSUBIMAGE1DPROC glad_glCopyTexSubImage1D
PFNGLCOPYTEXSUBIMAGE2DPROC glad_glCopyTexSubImage2D
PFNGLCOPYTEXSUBIMAGE3DPROC glad_glCopyTexSubImage3D
PFNGLCREATEPROGRAMPROC glad_glCreateProgram
PFNGLCREATESHADERPROC glad_glCreateShader
PFNGLCULLFACEPROC glad_glCullFace
PFNGLDELETEBUFFERSPROC glad_glDeleteBuffers
PFNGLDELETEFRAMEBUFFERSPROC glad_glDeleteFramebuffers
PFNGLDELETEPROGRAMPROC glad_glDeleteProgram
PFNGLDELETEQUERIESPROC glad_glDeleteQueries
PFNGLDELETERENDERBUFFERSPROC glad_glDeleteRenderbuffers
PFNGLDELETESAMPLERSPROC glad_glDeleteSamplers
PFNGLDELETESHADERPROC glad_glDeleteShader
PFNGLDELETESYNCPROC glad_glDeleteSync
PFNGLDELETETEXTURESPROC glad_glDeleteTextures
PFNGLDELETEVERTEXARRAYSPROC glad_glDeleteVertexArrays
PFNGLDEPTHFUNCPROC glad_glDepthFunc
PFNGLDEPTHMASKPROC glad_glDepthMask
PFNGLDEPTHRANGEPROC glad_glDepthRange
PFNGLDETACHSHADERPROC glad_glDetachShader
PFNGLDISABLEPROC glad_glDisable
PFNGLDISABLEVERTEXATTRIBARRAYPROC glad_glDisableVertexAttribArray
PFNGLDISABLEIPROC glad_glDisablei
PFNGLDRAWARRAYSPROC glad_glDrawArrays
PFNGLDRAWARRAYSINSTANCEDPROC glad_glDrawArraysInstanced
PFNGLDRAWBUFFERPROC glad_glDrawBuffer
PFNGLDRAWBUFFERSPROC glad_glDrawBuffers
PFNGLDRAWELEMENTSPROC glad_glDrawElements
PFNGLDRAWELEMENTSBASEVERTEXPROC glad_glDrawElementsBaseVertex
PFNGLDRAWELEMENTSINSTANCEDPROC glad_glDrawElementsInstanced
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glad_glDrawElementsInstancedBaseVertex
PFNGLDRAWRANGEELEMENTSPROC glad_glDrawRangeElements
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glad_glDrawRangeElementsBaseVertex
PFNGLENABLEPROC glad_glEnable
PFNGLENABLEVERTEXATTRIBARRAYPROC glad_glEnableVertexAttribArray
PFNGLENABLEIPROC glad_glEnablei
PFNGLENDCONDITIONALRENDERPROC glad_glEndConditionalRender
PFNGLENDQUERYPROC glad_glEndQuery
PFNGLENDTRANSFORMFEEDBACKPROC glad_glEndTransformFeedback
PFNGLFENCESYNCPROC glad_glFenceSync
PFNGLFINISHPROC glad_glFinish
PFNGLFLUSHPROC glad_glFlush
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glad_glFlushMappedBufferRange
PFNGLFRAMEBUFFERRENDERBUFFERPROC glad_glFramebufferRenderbuffer
PFNGLFRAMEBUFFERTEXTUREPROC glad_glFramebufferTexture
PFNGLFRAMEBUFFERTEXTURE1DPROC glad_glFramebufferTexture1D
PFNGLFRAMEBUFFERTEXTURE2DPROC glad_glFramebufferTexture2D
PFNGLFRAMEBUFFERTEXTURE3DPROC glad_glFramebufferTexture3D
PFNGLFRAMEBUFFERTEXTURELAYERPROC glad_glFramebufferTextureLayer
PFNGLFRONTFACEPROC glad_glFrontFace
PFNGLGENBUFFERSPROC glad_glGenBuffers
PFNGLGENFRAMEBUFFERSPROC glad_glGenFramebuffers
PFNGLGENQUERIESPROC glad_glGenQueries
PFNGLGENRENDERBUFFERSPROC glad_glGenRenderbuffers
PFNGLGENSAMPLERSPROC glad_glGenSamplers
PFNGLGENTEXTURESPROC glad_glGenTextures
PFNGLGENVERTEXARRAYSPROC glad_glGenVertexArrays
PFNGLGENERATEMIPMAPPROC glad_glGenerateMipmap
PFNGLGETACTIVEATTRIBPROC glad_glGetActiveAttrib
PFNGLGETACTIVEUNIFORMPROC glad_glGetActiveUniform
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glad_glGetActiveUniformBlockName
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glad_glGetActiveUniformBlockiv
PFNGLGETACTIVEUNIFORMNAMEPROC glad_glGetActiveUniformName
PFNGLGETACTIVEUNIFORMSIVPROC glad_glGetActiveUniformsiv
PFNGLGETATTACHEDSHADERSPROC glad_glGetAttachedShaders
PFNGLGETATTRIBLOCATIONPROC glad_glGetAttribLocation
PFNGLGETBOOLEANI_VPROC glad_glGetBooleani_v
PFNGLGETBOOLEANVPROC glad_glGetBooleanv
PFNGLGETBUFFERPARAMETERI64VPROC glad_glGetBufferParameteri64v
PFNGLGETBUFFERPARAMETERIVPROC glad_glGetBufferParameteriv
PFNGLGETBUFFERPOINTERVPROC glad_glGetBufferPointerv
PFNGLGETBUFFERSUBDATAPROC glad_glGetBufferSubData
PFNGLGETCOMPRESSEDTEXIMAGEPROC glad_glGetCompressedTexImage
PFNGLGETDOUBLEVPROC glad_glGetDoublev
PFNGLGETERRORPROC glad_glGetError
PFNGLGETFLOATVPROC glad_glGetFloatv
PFNGLGETFRAGDATAINDEXPROC glad_glGetFragDataIndex
PFNGLGETFRAGDATALOCATIONPROC glad_glGetFragDataLocation
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glad_glGetFramebufferAttachmentParameteriv
PFNGLGETINTEGER64I_VPROC glad_glGetInteger64i_v
PFNGLGETINTEGER64VPROC glad_glGetInteger64v
PFNGLGETINTEGERI_VPROC glad_glGetIntegeri_v
PFNGLGETINTEGERVPROC glad_glGetIntegerv
PFNGLGETMULTISAMPLEFVPROC glad_glGetMultisamplefv
PFNGLGETPROGRAMINFOLOGPROC glad_glGetProgramInfoLog
PFNGLGETPROGRAMIVPROC glad_glGetProgramiv
PFNGLGETQUERYOBJECTI64VPROC glad_glGetQueryObjecti64v
PFNGLGETQUERYOBJECTIVPROC glad_glGetQueryObjectiv
PFNGLGETQUERYOBJECTUI64VPROC glad_glGetQueryObjectui64v
PFNGLGETQUERYOBJECTUIVPROC glad_glGetQueryObjectuiv
PFNGLGETQUERYIVPROC glad_glGetQueryiv
PFNGLGETRENDERBUFFERPARAMETERIVPROC glad_glGetRenderbufferParameteriv
PFNGLGETSAMPLERPARAMETERIIVPROC glad_glGetSamplerParameterIiv
PFNGLGETSAMPLERPARAMETERIUIVPROC glad_glGetSamplerParameterIuiv
PFNGLGETSAMPLERPARAMETERFVPROC glad_glGetSamplerParameterfv
PFNGLGETSAMPLERPARAMETERIVPROC glad_glGetSamplerParameteriv
PFNGLGETSHADERINFOLOGPROC glad_glGetShaderInfoLog
PFNGLGETSHADERSOURCEPROC glad_glGetShaderSource
PFNGLGETSHADERIVPROC glad_glGetShaderiv
PFNGLGETSTRINGPROC glad_glGetString
PFNGLGETSTRINGIPROC glad_glGetStringi
PFNGLGETSYNCIVPROC glad_glGetSynciv
PFNGLGETTEXIMAGEPROC glad_glGetTexImage
PFNGLGETTEXLEVELPARAMETERFVPROC glad_glGetTexLevelParameterfv
PFNGLGETTEXLEVELPARAMETERIVPROC glad_glGetTexLevelParameteriv
PFNGLGETTEXPARAMETERIIVPROC glad_glGetTexParameterIiv
PFNGLGETTEXPARAMETERIUIVPROC glad_glGetTexParameterIuiv
PFNGLGETTEXPARAMETERFVPROC glad_glGetTexParameterfv
PFNGLGETTEXPARAMETERIVPROC glad_glGetTexParameteriv
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glad_glGetTransformFeedbackVarying
PFNGLGETUNIFORMBLOCKINDEXPROC glad_glGetUniformBlockIndex
PFNGLGETUNIFORMINDICESPROC glad_glGetUniformIndices
PFNGLGETUNIFORMLOCATIONPROC glad_glGetUniformLocation
PFNGLGETUNIFORMFVPROC glad_glGetUniformfv
PFNGLGETUNIFORMIVPROC glad_glGetUniformiv
PFNGLGETUNIFORMUIVPROC glad_glGetUniformuiv
PFNGLGETVERTEXATTRIBIIVPROC glad_glGetVertexAttribIiv
PFNGLGETVERTEXATTRIBIUIVPROC glad_glGetVertexAttribIuiv
PFNGLGETVERTEXATTRIBPOINTERVPROC glad_glGetVertexAttribPointerv
PFNGLGETVERTEXATTRIBDVPROC glad_glGetVertexAttribdv
PFNGLGETVERTEXATTRIBFVPROC glad_glGetVertexAttribfv
PFNGLGETVERTEXATTRIBIVPROC glad_glGetVertexAttribiv
PFNGLHINTPROC glad_glHint
PFNGLISBUFFERPROC glad_glIsBuffer
PFNGLISENABLEDPROC glad_glIsEnabled
PFNGLISENABLEDIPROC glad_glIsEnabledi
PFNGLISFRAMEBUFFERPROC glad_glIsFramebuffer
PFNGLISPROGRAMPROC glad_glIsProgram
PFNGLISQUERYPROC glad_glIsQuery
PFNGLISRENDERBUFFERPROC glad_glIsRenderbuffer
PFNGLISSAMPLERPROC glad_glIsSampler
PFNGLISSHADERPROC glad_glIsShader
PFNGLISSYNCPROC glad_glIsSync
PFNGLISTEXTUREPROC glad_glIsTexture
PFNGLISVERTEXARRAYPROC glad_glIsVertexArray
PFNGLLINEWIDTHPROC glad_glLineWidth
PFNGLLINKPROGRAMPROC glad_glLinkProgram
PFNGLLOGICOPPROC glad_glLogicOp
PFNGLMAPBUFFERPROC glad_glMapBuffer
PFNGLMAPBUFFERRANGEPROC glad_glMapBufferRange
PFNGLMULTIDRAWARRAYSPROC glad_glMultiDrawArrays
PFNGLMULTIDRAWELEMENTSPROC glad_glMultiDrawElements
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glad_glMultiDrawElementsBaseVertex
PFNGLMULTITEXCOORDP1UIPROC glad_glMultiTexCoordP1ui
PFNGLMULTITEXCOORDP1UIVPROC glad_glMultiTexCoordP1uiv
PFNGLMULTITEXCOORDP2UIPROC glad_glMultiTexCoordP2ui
PFNGLMULTITEXCOORDP2UIVPROC glad_glMultiTexCoordP2uiv
PFNGLMULTITEXCOORDP3UIPROC glad_glMultiTexCoordP3ui
PFNGLMULTITEXCOORDP3UIVPROC glad_glMultiTexCoordP3uiv
PFNGLMULTITEXCOORDP4UIPROC glad_glMultiTexCoordP4ui
PFNGLMULTITEXCOORDP4UIVPROC glad_glMultiTexCoordP4uiv
PFNGLNORMALP3UIPROC glad_glNormalP3ui
PFNGLNORMALP3UIVPROC glad_glNormalP3uiv
PFNGLPIXELSTOREFPROC glad_glPixelStoref
PFNGLPIXELSTOREIPROC glad_glPixelStorei
PFNGLPOINTPARAMETERFPROC glad_glPointParameterf
PFNGLPOINTPARAMETERFVPROC glad_glPointParameterfv
PFNGLPOINTPARAMETERIPROC glad_glPointParameteri
PFNGLPOINTPARAMETERIVPROC glad_glPointParameteriv
PFNGLPOINTSIZEPROC glad_glPointSize
PFNGLPOLYGONMODEPROC glad_glPolygonMode
PFNGLPOLYGONOFFSETPROC glad_glPolygonOffset
PFNGLPRIMITIVERESTARTINDEXPROC glad_glPrimitiveRestartIndex
PFNGLPROVOKINGVERTEXPROC glad_glProvokingVertex
PFNGLQUERYCOUNTERPROC glad_glQueryCounter
PFNGLREADBUFFERPROC glad_glReadBuffer
PFNGLREADPIXELSPROC glad_glReadPixels
PFNGLRENDERBUFFERSTORAGEPROC glad_glRenderbufferStorage
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glad_glRenderbufferStorageMultisample
PFNGLSAMPLECOVERAGEPROC glad_glSampleCoverage
PFNGLSAMPLEMASKIPROC glad_glSampleMaski
PFNGLSAMPLERPARAMETERIIVPROC glad_glSamplerParameterIiv
PFNGLSAMPLERPARAMETERIUIVPROC glad_glSamplerParameterIuiv
PFNGLSAMPLERPARAMETERFPROC glad_glSamplerParameterf
PFNGLSAMPLERPARAMETERFVPROC glad_glSamplerParameterfv
PFNGLSAMPLERPARAMETERIPROC glad_glSamplerParameteri
PFNGLSAMPLERPARAMETERIVPROC glad_glSamplerParameteriv
PFNGLSCISSORPROC glad_glScissor
PFNGLSECONDARYCOLORP3UIPROC glad_glSecondaryColorP3ui
PFNGLSECONDARYCOLORP3UIVPROC glad_glSecondaryColorP3uiv
PFNGLSHADERSOURCEPROC glad_glShaderSource
PFNGLSTENCILFUNCPROC glad_glStencilFunc
PFNGLSTENCILFUNCSEPARATEPROC glad_glStencilFuncSeparate
PFNGLSTENCILMASKPROC glad_glStencilMask
PFNGLSTENCILMASKSEPARATEPROC glad_glStencilMaskSeparate
PFNGLSTENCILOPPROC glad_glStencilOp
PFNGLSTENCILOPSEPARATEPROC glad_glStencilOpSeparate
PFNGLTEXBUFFERPROC glad_glTexBuffer
PFNGLTEXCOORDP1UIPROC glad_glTexCoordP1ui
PFNGLTEXCOORDP1UIVPROC glad_glTexCoordP1uiv
PFNGLTEXCOORDP2UIPROC glad_glTexCoordP2ui
PFNGLTEXCOORDP2UIVPROC glad_glTexCoordP2uiv
PFNGLTEXCOORDP3UIPROC glad_glTexCoordP3ui
PFNGLTEXCOORDP3UIVPROC glad_glTexCoordP3uiv
PFNGLTEXCOORDP4UIPROC glad_glTexCoordP4ui
PFNGLTEXCOORDP4UIVPROC glad_glTexCoordP4uiv
PFNGLTEXIMAGE1DPROC glad_glTexImage1D
PFNGLTEXIMAGE2DPROC glad_glTexImage2D
PFNGLTEXIMAGE2DMULTISAMPLEPROC glad_glTexImage2DMultisample
PFNGLTEXIMAGE3DPROC glad_glTexImage3D
PFNGLTEXIMAGE3DMULTISAMPLEPROC glad_glTexImage3DMultisample
PFNGLTEXPARAMETERIIVPROC glad_glTexParameterIiv
PFNGLTEXPARAMETERIUIVPROC glad_glTexParameterIuiv
PFNGLTEXPARAMETERFPROC glad_glTexParameterf
PFNGLTEXPARAMETERFVPROC glad_glTexParameterfv
PFNGLTEXPARAMETERIPROC glad_glTexParameteri
PFNGLTEXPARAMETERIVPROC glad_glTexParameteriv
PFNGLTEXSUBIMAGE1DPROC glad_glTexSubImage1D
PFNGLTEXSUBIMAGE2DPROC glad_glTexSubImage2D
PFNGLTEXSUBIMAGE3DPROC glad_glTexSubImage3D
PFNGLTRANSFORMFEEDBACKVARYINGSPROC glad_glTransformFeedbackVaryings
PFNGLUNIFORM1FPROC glad_glUniform1f
PFNGLUNIFORM1FVPROC glad_glUniform1fv
PFNGLUNIFORM1IPROC glad_glUniform1i
PFNGLUNIFORM1IVPROC glad_glUniform1iv
PFNGLUNIFORM1UIPROC glad_glUniform1ui
PFNGLUNIFORM1UIVPROC glad_glUniform1uiv
PFNGLUNIFORM2FPROC glad_glUniform2f
PFNGLUNIFORM2FVPROC glad_glUniform2fv
PFNGLUNIFORM2IPROC glad_glUniform2i
PFNGLUNIFORM2IVPROC glad_glUniform2iv
PFNGLUNIFORM2UIPROC glad_glUniform2ui
PFNGLUNIFORM2UIVPROC glad_glUniform2uiv
PFNGLUNIFORM3FPROC glad_glUniform3f
PFNGLUNIFORM3FVPROC glad_glUniform3fv
PFNGLUNIFORM3IPROC glad_glUniform3i
PFNGLUNIFORM3IVPROC glad_glUniform3iv
PFNGLUNIFORM3UIPROC glad_glUniform3ui
PFNGLUNIFORM3UIVPROC glad_glUniform3uiv
PFNGLUNIFORM4FPROC glad_glUniform4f
PFNGLUNIFORM4FVPROC glad_glUniform4fv
PFNGLUNIFORM4IPROC glad_glUniform4i
PFNGLUNIFORM4IVPROC glad_glUniform4iv
PFNGLUNIFORM4UIPROC glad_glUniform4ui
PFNGLUNIFORM4UIVPROC glad_glUniform4uiv
PFNGLUNIFORMBLOCKBINDINGPROC glad_glUniformBlockBinding
PFNGLUNIFORMMATRIX2FVPROC glad_glUniformMatrix2fv
PFNGLUNIFORMMATRIX2X3FVPROC glad_glUniformMatrix2x3fv
PFNGLUNIFORMMATRIX2X4FVPROC glad_glUniformMatrix2x4fv
PFNGLUNIFORMMATRIX3FVPROC glad_glUniformMatrix3fv
PFNGLUNIFORMMATRIX3X2FVPROC glad_glUniformMatrix3x2fv
PFNGLUNIFORMMATRIX3X4FVPROC glad_glUniformMatrix3x4fv
PFNGLUNIFORMMATRIX4FVPROC glad_glUniformMatrix4fv
PFNGLUNIFORMMATRIX4X2FVPROC glad_glUniformMatrix4x2fv
PFNGLUNIFORMMATRIX4X3FVPROC glad_glUniformMatrix4x3fv
PFNGLUNMAPBUFFERPROC glad_glUnmapBuffer
PFNGLUSEPROGRAMPROC glad_glUseProgram
PFNGLVALIDATEPROGRAMPROC glad_glValidateProgram
PFNGLVERTEXATTRIB1DPROC glad_glVertexAttrib1d
PFNGLVERTEXATTRIB1DVPROC glad_glVertexAttrib1dv
PFNGLVERTEXATTRIB1FPROC glad_glVertexAttrib1f
PFNGLVERTEXATTRIB1FVPROC glad_glVertexAttrib1fv
PFNGLVERTEXATTRIB1SPROC glad_glVertexAttrib1s
PFNGLVERTEXATTRIB1SVPROC glad_glVertexAttrib1sv
PFNGLVERTEXATTRIB2DPROC glad_glVertexAttrib2d
PFNGLVERTEXATTRIB2DVPROC glad_glVertexAttrib2dv
PFNGLVERTEXATTRIB2FPROC glad_glVertexAttrib2f
PFNGLVERTEXATTRIB2FVPROC glad_glVertexAttrib2fv
PFNGLVERTEXATTRIB2SPROC glad_glVertexAttrib2s
PFNGLVERTEXATTRIB2SVPROC glad_glVertexAttrib2sv
PFNGLVERTEXATTRIB3DPROC glad_glVertexAttrib3d
PFNGLVERTEXATTRIB3DVPROC glad_glVertexAttrib3dv
PFNGLVERTEXATTRIB3FPROC glad_glVertexAttrib3f
PFNGLVERTEXATTRIB3FVPROC glad_glVertexAttrib3fv
PFNGLVERTEXATTRIB3SPROC glad_glVertexAttrib3s
PFNGLVERTEXATTRIB3SVPROC glad_glVertexAttrib3sv
PFNGLVERTEXATTRIB4NBVPROC glad_glVertexAttrib4Nbv
PFNGLVERTEXATTRIB4NIVPROC glad_glVertexAttrib4Niv
PFNGLVERTEXATTRIB4NSVPROC glad_glVertexAttrib4Nsv
PFNGLVERTEXATTRIB4NUBPROC glad_glVertexAttrib4Nub
PFNGLVERTEXATTRIB4NUBVPROC glad_glVertexAttrib4Nubv
PFNGLVERTEXATTRIB4NUIVPROC glad_glVertexAttrib4Nuiv
PFNGLVERTEXATTRIB4NUSVPROC glad_glVertexAttrib4Nusv
PFNGLVERTEXATTRIB4BVPROC glad_glVertexAttrib4bv
PFNGLVERTEXATTRIB4DPROC glad_glVertexAttrib4d
PFNGLVERTEXATTRIB4DVPROC glad_glVertexAttrib4dv
PFNGLVERTEXATTRIB4FPROC glad_glVertexAttrib4f
PFNGLVERTEXATTRIB4FVPROC glad_glVertexAttrib4fv
PFNGLVERTEXATTRIB4IVPROC glad_glVertexAttrib4iv
PFNGLVERTEXATTRIB4SPROC glad_glVertexAttrib4s
PFNGLVERTEXATTRIB4SVPROC glad_glVertexAttrib4sv
PFNGLVERTEXATTRIB4UBVPROC glad_glVertexAttrib4ubv
PFNGLVERTEXATTRIB4UIVPROC glad_glVertexAttrib4uiv
PFNGLVERTEXATTRIB4USVPROC glad_glVertexAttrib4usv
PFNGLVERTEXATTRIBDIVISORPROC glad_glVertexAttribDivisor
PFNGLVERTEXATTRIBI1IPROC glad_glVertexAttribI1i
PFNGLVERTEXATTRIBI1IVPROC glad_glVertexAttribI1iv
PFNGLVERTEXATTRIBI1UIPROC glad_glVertexAttribI1ui
PFNGLVERTEXATTRIBI1UIVPROC glad_glVertexAttribI1uiv
PFNGLVERTEXATTRIBI2IPROC glad_glVertexAttribI2i
PFNGLVERTEXATTRIBI2IVPROC glad_glVertexAttribI2iv
PFNGLVERTEXATTRIBI2UIPROC glad_glVertexAttribI2ui
PFNGLVERTEXATTRIBI2UIVPROC glad_glVertexAttribI2uiv
PFNGLVERTEXATTRIBI3IPROC glad_glVertexAttribI3i
PFNGLVERTEXATTRIBI3IVPROC glad_glVertexAttribI3iv
PFNGLVERTEXATTRIBI3UIPROC glad_glVertexAttribI3ui
PFNGLVERTEXATTRIBI3UIVPROC glad_glVertexAttribI3uiv
PFNGLVERTEXATTRIBI4BVPROC glad_glVertexAttribI4bv
PFNGLVERTEXATTRIBI4IPROC glad_glVertexAttribI4i
PFNGLVERTEXATTRIBI4IVPROC glad_glVertexAttribI4iv
PFNGLVERTEXATTRIBI4SVPROC glad_glVertexAttribI4sv
PFNGLVERTEXATTRIBI4UBVPROC glad_glVertexAttribI4ubv
PFNGLVERTEXATTRIBI4UIPROC glad_glVertexAttribI4ui
PFNGLVERTEXATTRIBI4UIVPROC glad_glVertexAttribI4uiv
PFNGLVERTEXATTRIBI4USVPROC glad_glVertexAttribI4usv
PFNGLVERTEXATTRIBIPOINTERPROC glad_glVertexAttribIPointer
PFNGLVERTEXATTRIBP1UIPROC glad_glVertexAttribP1ui
PFNGLVERTEXATTRIBP1UIVPROC glad_glVertexAttribP1uiv
PFNGLVERTEXATTRIBP2UIPROC glad_glVertexAttribP2ui
PFNGLVERTEXATTRIBP2UIVPROC glad_glVertexAttribP2uiv
PFNGLVERTEXATTRIBP3UIPROC glad_glVertexAttribP3ui
PFNGLVERTEXATTRIBP3UIVPROC glad_glVertexAttribP3uiv
PFNGLVERTEXATTRIBP4UIPROC glad_glVertexAttribP4ui
PFNGLVERTEXATTRIBP4UIVPROC glad_glVertexAttribP4uiv
PFNGLVERTEXATTRIBPOINTERPROC glad_glVertexAttribPointer
PFNGLVERTEXP2UIPROC glad_glVertexP2ui
PFNGLVERTEXP2UIVPROC glad_glVertexP2uiv
PFNGLVERTEXP3UIPROC glad_glVertexP3ui
PFNGLVERTEXP3UIVPROC glad_glVertexP3uiv
PFNGLVERTEXP4UIPROC glad_glVertexP4ui
PFNGLVERTEXP4UIVPROC glad_glVertexP4uiv
PFNGLVIEWPORTPROC glad_glViewport
PFNGLWAITSYNCPROC glad_glWaitSync
static void * get_proc(const char *namez)
References gladGetProcAddressPtr, libGL.
Referenced by gladLoadGL.
static int open_gl(void)
Referenced by gladLoadGL.
static void close_gl(void)
Referenced by gladLoadGL.
int gladLoadGL(void)
References close_gl, get_proc, gladLoadGLLoader, open_gl.
static int get_exts(void)
References exts_i.
Referenced by find_extensionsGL.
static void free_exts(void)
References num_exts_i.
Referenced by find_extensionsGL.
static int has_ext(const char *ext)
References exts, num_exts_i.
Referenced by find_extensionsGL.
static void load_GL_VERSION_1_0(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_1(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_2(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_3(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_4(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_5(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_2_0(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_2_1(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_0(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_1(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_2(GLADloadproc load)
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_3(GLADloadproc load)
Referenced by gladLoadGLLoader.
static int find_extensionsGL(void)
References free_exts, get_exts, has_ext.
Referenced by gladLoadGLLoader.
static void find_coreGL(void)
Referenced by gladLoadGLLoader.
int gladLoadGLLoader(GLADloadproc load)
References find_coreGL, find_extensionsGL, load_GL_VERSION_1_0, load_GL_VERSION_1_1, load_GL_VERSION_1_2, load_GL_VERSION_1_3, load_GL_VERSION_1_4, load_GL_VERSION_1_5, load_GL_VERSION_2_0, load_GL_VERSION_2_1, load_GL_VERSION_3_0, load_GL_VERSION_3_1, load_GL_VERSION_3_2, load_GL_VERSION_3_3.