Archetype
ArchetypeType Archetype::type
Referenced by Archetype, getType.
std::vector< ComponentType > Archetype::components
Referenced by Archetype, getComponentTypesArrayCopy.
Archetype::Archetype()
References type.
Archetype::Archetype(ArchetypeType type, std::vector< ComponentType > components)
References components, type.
ArchetypeType Archetype::getType() const
References type.
Referenced by ChunkManager::assignNewEntity, operator<<.
const std::vector< ComponentType > Archetype::getComponentTypesArrayCopy() const
References components.
Referenced by Chunk::addComponentArrays, operator<<, EntityQuery::searchChunks.
Archetype::Archetype()
Archetype::Archetype(ArchetypeType type, std::vector< ComponentType > components)
ArchetypeType Archetype::getType() const
const std::vector<ComponentType> Archetype::getComponentTypesArrayCopy() const