Chunk
ChunkManager
int Chunk::chunkID
Referenced by assignNewEntity, Chunk.
Signature Chunk::sig
Referenced by Chunk.
Archetype Chunk::arch
Referenced by Chunk, getArchetype.
Spritesheet Chunk::spritesheet
Referenced by Chunk, GetSpritesheet.
int Chunk::currEnts
Referenced by assignNewEntity, getCurrEntCount, releaseEntity.
std::unordered_map< ComponentType, Byte * > Chunk::componentArrays
Referenced by addComponentArray, addComponentArrays, getComponentArray, releaseEntity, ~Chunk.
int Chunk::versions[ENTITIES_PER_CHUNK]
Referenced by assignNewEntity, releaseEntity.
int Chunk::entToDat[ENTITIES_PER_CHUNK]
Referenced by assignNewEntity, Chunk, getComponentReference, releaseEntity.
int Chunk::datToEnt[ENTITIES_PER_CHUNK]
Referenced by assignNewEntity, releaseEntity.
Chunk::Chunk(Signature sig, int chunkID, Spritesheet spriteSheet)
References chunkID, sig, spritesheet.
Chunk::Chunk(Archetype archetype, int chunkID, Spritesheet spriteSheet, ComponentSizeMap &sizemap)
References addComponentArrays, arch, chunkID, ENTITIES_PER_CHUNK, entToDat, spritesheet.
void Chunk::addComponentArrays(Archetype t, ComponentSizeMap &sizemap)
References componentArrays, ENTITIES_PER_CHUNK, Archetype::getComponentTypesArrayCopy.
Referenced by Chunk.
void Chunk::addComponentArray()
References componentArrays, ENTITIES_PER_CHUNK.
Referenced by addComponentArray.
void Chunk::addComponentArray()
References addComponentArray, componentArrays, ENTITIES_PER_CHUNK.
Chunk::Chunk(Signature sig, int chunkID, Spritesheet spriteSheet)
Chunk::Chunk(Archetype archetype, int chunkID, Spritesheet spriteSheet, ComponentSizeMap &sizemap)
void Chunk::addComponentArrays(Archetype t, ComponentSizeMap &sizemap)
void Chunk::addComponentArray()
void Chunk::addComponentArray()
Chunk::Chunk()=delete
Spritesheet Chunk::GetSpritesheet()
References spritesheet.
Referenced by ChunkManager::assignNewEntity.
int Chunk::getCurrEntCount()
References currEnts.
Referenced by ChunkManager::assignNewEntity.
ChunkAddress Chunk::assignNewEntity()
References chunkID, ChunkAddress::chunkID, currEnts, datToEnt, ENTITIES_PER_CHUNK, entToDat, versions.
Referenced by ChunkManager::assignNewEntity.
void Chunk::releaseEntity(ChunkAddress id)
References componentArrays, currEnts, datToEnt, entToDat, versions.
T & Chunk::getComponentReference(ChunkAddress id)
References ENTITIES_PER_CHUNK, entToDat.
T * Chunk::getComponentArray()
References componentArrays.
Archetype Chunk::getArchetype()
References arch.
Chunk::~Chunk()
References componentArrays.
Chunk::Chunk()=delete
const char* Chunk::GetSpritesheet()
int Chunk::getCurrEntCount()
ChunkAddress Chunk::assignNewEntity()
void Chunk::releaseEntity(ChunkAddress id)
T& Chunk::getComponentReference(ChunkAddress id)
T* Chunk::getComponentArray()
Archetype Chunk::getArchetype()
Chunk::~Chunk()