FileManager
stbi_uc * FileManager::readImageFile(const char *fileName, int *width, int *height, int *colorChannels)
Referenced by Renderer::loadImages.
std::string FileManager::readTextFile(const char *fileName)
Referenced by readShaderFile.
std::string FileManager::readShaderFile(const char *fileName)
References readTextFile.
Referenced by Renderer::createDefaultShaderProgram.